[features]
seeds = false
[programs.devnet]
inter_dao = "7BxgcaPHKcowjbjA2LjsMNNUaWB3dPFQ9Zn1nChNcm5C"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/tuphan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
